language: python

python:
  - "3.5"

sudo: required
dist: trusty

services:
  - docker

before_install:
  - sudo apt-get update
  - sudo apt-get -y install liblua5.1-dev libffi-dev
  - pushd db
  - docker build -t faf-db .
  - docker run -d --name faf-db -e MYSQL_ROOT_PASSWORD=banana faf-db
  - docker logs faf-db
  - docker exec -i faf-db mysql -h127.0.0.1 -uroot -pbanana < db-structure.sql
  - docker exec -i faf-db mysql -h127.0.0.1 -uroot -pbanana < db-data.sql
  - popd
  - cp config.example.py config.py

install:
  - docker build -t faf-api .

script:
  - docker run --link faf-db:db faf-api py.test --cov-report term-missing --cov=api
  - docker run --link faf-db:db faf-api pyflakes . || true

after_success:
  - docker run --link faf-db:db faf-api coveralls
