language: python

python:
  - "3.5"

sudo: required
dist: trusty

before_install:
  - sudo apt-get update
  - sudo apt-get install debconf-utils
  - sudo debconf-set-selections <<< 'mysql-server mysql-server/root_password password'
  - sudo debconf-set-selections <<< 'mysql-server mysql-server/root_password_again password'
  - sudo apt-get -y install mysql-client-5.6 mysql-client-core-5.6 mysql-server-core-5.6 liblua5.1-dev libffi-dev
  - sudo service mysql start

install:
  - cp config.example.py config.py
  - "pip install --upgrade pip"
  - "pip install --trusted-host content.dev.faforever.com -r requirements.txt"
  - "pip install -e db"

before_script:
  - "mysql -uroot -e 'create database faf_test;'"
  - "mysql -uroot faf_test < db/db-structure.sql"
  - "mysql -uroot faf_test < db/db-data.sql"

script:
  - pip install -e .
  - py.test --cov-report term-missing --cov=api
  - pyflakes . || true

after_success:
  - coveralls
