language: python

python:
  - "3.5"

sudo: required
dist: trusty

services:
  - docker

before_install:
  - sudo apt-get update
  - sudo apt-get -y install liblua5.1-dev libffi-dev
  - pushd db
  - docker build -t faf-db .
  - docker run -d --name faf-db -e MYSQL_ROOT_PASSWORD=banana faf-db
  - docker exec -i faf-db mysql -uroot -pbanana < db-structure.sql
  - docker exec -i faf-db mysql -uroot -pbanana < db-data.sql
  - popd

install:
  - cp config.example.py config.py
  - "pip install --upgrade pip"
  - "pip install --trusted-host content.dev.faforever.com -r requirements.txt"
  - "pip install -e db"

before_script:
  - "mysql -uroot -e 'create database faf_test;'"
  - "mysql -uroot faf_test < db/db-structure.sql"
  - "mysql -uroot faf_test < db/db-data.sql"

script:
  - pip install -e .
  - py.test --cov-report term-missing --cov=api
  - pyflakes . || true

after_success:
  - coveralls
